#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HARK_REPO == "BLACKSHARKUSERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $HARK_REPO == "Blackshark" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $HARK_REPO =~ $regex ]]
    then
        if [[ $HARK_REPO_FORK ]]
        then
            echo "${HARK_REPO}/archive/${HARK_REPO_FORK}.zip"
        else
            echo "${HARK_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Blackshark.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    SharkPath=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $SharkPath
    echo "    Starting BLACKSHARK   "
    echo "
                              𝔹𝕃𝔸ℂ𝕂 𝕊ℍ𝔸ℝ𝕂 𝕌𝕊𝔼ℝ𝔹𝕆𝕋
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

start_bot
