#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HELL_REPO == "HellBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $HELL_REPO == "Hellbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $HELL_REPO =~ $regex ]]
    then
        if [[ $HELL_REPO_BRANCH ]]
        then
            echo "${HELL_REPO}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${HELL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3B1c2hwZW5kcmE2MzY3L0RhcmstYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Blackshark.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "    Starting BLACKSHARK   "
    echo "
                              𝔹𝕃𝔸ℂ𝕂 𝕊ℍ𝔸ℝ𝕂 𝕌𝕊𝔼ℝ𝔹𝕆𝕋
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
