#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $BLACK_REPO == "BLACKSHARK" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $BLACK_REPO == "BLACKSHARK" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $BALCK_REPO =~ $regex ]]
    then
        if [[ $Black_REPO_BRANCH ]]
        then
            echo "${BLACK_REPO}/archive/${Black_REPO_BRANCH}.zip"
        else
            echo "${BLACK_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Blackbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    BLACKPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $BLACKPATH
    echo "    Starting BLACKSHARK USERBOT  "
    echo "
                   𝔹𝕃𝔸ℂ𝕂 𝕊ℍ𝔸ℝ𝕂 𝕌𝕊𝔼ℝ𝔹𝕆𝕋           

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
